[env:watchy]
platform = espressif32@~6.6.0
board = watchy
framework = arduino
monitor_speed = 921600
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
build_flags = -DCORE_DEBUG_LEVEL=0 -DARDUINO_WATCHY_V20
board_build.partitions = min_spiffs.csv
lib_deps =
  adafruit/Adafruit GFX Library@^1.10.10
  arduino-libraries/Arduino_JSON@^0.1.0
  jchristensen/DS3232RTC@^2.0.0
  zinggjm/GxEPD2@^1.5.1
  https://github.com/tzapu/WiFiManager.git#v2.0.11-beta
  adafruit/Adafruit BusIO@^1.8.2
  sqfmi/Watchy@^1.4.6